### PR TITLE
Support rtl

### LINKED ISSUE #17: Right to left layout breaks the button
Right to left layout breaks the button moves the button to the center.

### PR DESCRIPTION
**Pull request by G00fY2**
I added a simple rtl detection logic and set the label position correspondingly. I also fixed a bug that caused calculating wrong margins when label position was on the right.

fixes #17

### CODE REVIEW

**Comment by jahirfiquitiva** [comment]
Thank you so much for the contribution.
Can you please post some screenshots? 😊

**Comment by G00fY2** [comment]
device-2018-01-01-172952

You can force RTL in the developer settings to test it by yourself. 😃

**Comment by jahirfiquitiva** [comment]
Looks good to me. I'm going to close this PR and merge #20 since it has these changes too.
Thank you so much for your help 😊🤗

**Comment by jahirfiquitiva** [comment]
Ups... I don't know why I saw these commits in #20... Well... Merging now. Thanks again 😅

**Comment by G00fY2** [comment]
You saw them because I accidentally merged both branches but undo/reset my `develop` branch right after I noticed it.

Sorry for the confusion. :sweat_smile:

**Pull request merged**
