### PR TITLE
Fix for #30

### PR DESCRIPTION
**Pull request by leinardi**
### Description
Fix for #30 Attribute fabSize ignored: the TitleFABs are always mini.

### Motivation
Check #30 for detail.

### CODE REVIEW

**Comment by jahirfiquitiva** [comment]
Thanks for the contribution. I forced the TitleFABs to be of size mini to keep consistency and difference between the MenuFAB and TitleFABs

**Comment by jahirfiquitiva** [comment]
I'll keep this one. If there's a good amount of people wanting this to be merged/included, then I will 🙂

**Comment by leinardi** [comment]
I see, can I suggest than to update the README.md and the sources to reflect this choice? Currently it seems that you can change the size since the gif animation, the How to implement sections and the sample app show the use of this feature.

PS
I rebased to solve the merge conflicts.

**Comment by jahirfiquitiva** [comment]
@leinardi 
Thanks for the suggestion. I will update it soon 🙂

**Comment by hannesa2** [comment]
@jahirfiquitiva why waiting? Please don't hesitate and merge it. 
Thank you

**Comment by hannesaa2** [comment]
I wait for this feature too

**Comment by jahirfiquitiva** [comment]
@leinardi 
I've merged this, but could you please help me updating the README to match your changes (if you consider it's needed)

Thanks in advance and thanks for your contributions :smile:

**Comment by leinardi** [comment]
Hi @jahirfiquitiva, there is no need to update the README because this PR was just fixing a bug so there is no change in the behavior of the library: now is actually doing what is written in the README :).

**Comment by jahirfiquitiva** [comment]
@leinardi 
Awesome .. Thanks for all the help :blush:

**Pull request merged**
